/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-primary-container": "#fffbff",
          "inverse-on-surface": "#f3f0ef",
          "on-secondary-fixed-variant": "#3b475f",
          "secondary-fixed-dim": "#bac7e4",
          "status-error": "#E04403",
          "primary-fixed": "#ffdbd0",
          "secondary-fixed": "#d7e3ff",
          "surface-container-highest": "#e5e2e1",
          "outline-variant": "#e4beb3",
          "outline": "#8f7067",
          "inverse-primary": "#ffb59e",
          "primary-container": "#d43f00",
          "inverse-surface": "#313030",
          "on-surface": "#1b1b1b",
          "surface-faint": "#F4F4F4",
          "on-primary-fixed": "#3a0b00",
          "secondary-container": "#d3e0fe",
          "surface-variant": "#e5e2e1",
          "on-background": "#1b1b1b",
          "on-error-container": "#93000a",
          "on-tertiary-fixed": "#00210f",
          "background": "#fcf9f8",
          "surface-tint": "#ae3200",
          "surface-container-low": "#f6f3f2",
          "status-success": "#346E4A",
          "secondary": "#525f78",
          "surface-container": "#f0eded",
          "on-secondary-container": "#56637c",
          "on-error": "#ffffff",
          "border-subtle": "#E0E0E0",
          "error-container": "#ffdad6",
          "tertiary-fixed-dim": "#97d4a9",
          "primary": "#aa3100",
          "on-surface-variant": "#5b4038",
          "on-tertiary-fixed-variant": "#145130",
          "primary-fixed-dim": "#ffb59e",
          "navy-muted": "#1C2B44",
          "on-tertiary": "#ffffff",
          "tertiary-fixed": "#b2f1c3",
          "on-tertiary-container": "#f6fff4",
          "surface-bright": "#fcf9f8",
          "surface": "#fcf9f8",
          "on-primary": "#ffffff",
          "surface-container-high": "#eae7e7",
          "on-primary-fixed-variant": "#852400",
          "surface-dim": "#dcd9d9",
          "on-secondary-fixed": "#0e1b31",
          "tertiary": "#2d6744",
          "surface-container-lowest": "#ffffff",
          "on-secondary": "#ffffff",
          "error": "#ba1a1a",
          "tertiary-container": "#46805b",
          "swift": {
            red: '#E30613',
            dark: '#111111',
            card: '#161616',
            border: '#222222',
            gold: '#F2A900'
          }
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "gutter": "24px",
          "margin-mobile": "16px",
          "sidebar-width": "260px",
          "margin-desktop": "32px",
          "base": "8px"
      },
      "fontFamily": {
          "data-tabular": ["JetBrains Mono", "monospace"],
          "body-md": ["Inter", "sans-serif"],
          "label-md": ["JetBrains Mono", "monospace"],
          "body-lg": ["Inter", "sans-serif"],
          "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
          "display-lg": ["Hanken Grotesk", "sans-serif"],
          "body-sm": ["Inter", "sans-serif"],
          "headline-lg": ["Hanken Grotesk", "sans-serif"],
          "headline-md": ["Hanken Grotesk", "sans-serif"]
      },
      "fontSize": {
          "data-tabular": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
          "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
          "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
          "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
          "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
          "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
